version: "3.4"

services:
  meteor:
    container_name: "meteor_test"
    build:
      context: .
      target: development
      args:
        port: "${PORT}"
        mongo_url: "${MONGO_URL}"
        root_url: "${ROOT_URL}"
    networks:
      - meteor-network
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env 
    volumes:
      - ./meteor/test-app:/app/
      - ./config/dev/:/settings
    depends_on:
      - mongo

  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    networks:
      - meteor-network
    volumes:
      - database1_volume:/data/db

networks: 
  meteor-network:
    driver: bridge

volumes:
  database1_volume: