FROM node:13 as base_image

ARG NODE_ENV="development"
ENV NODE_ENV=${NODE_ENV}

ARG MONGO_URL="mongodb://localhost:27017/myappdb"
ENV MONGO_URL=${MONGO_URL}

ARG PORT="3000"
ENV PORT=${PORT}

ARG ROOT_URL="http://localhost:3000"
ENV ROOT_URL=${ROOT_URL}

ENV METEOR_ALLOW_SUPERUSER=true

RUN mkdir /app
WORKDIR /app

RUN curl https://install.meteor.com/ | sh

COPY . .

RUN meteor build ../ --directory --server-only
RUN cd ../bundle/programs/server && npm install

EXPOSE 3000
CMD [ "node", "/bundle/main.js" ]